import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider"
 
// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })
import "./globals.css";
import { ModeToggle } from '@/components/ui/mode';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
